### ISSUE TITLE
Multiplying VNF Packages for use case

### ISSUE THREAD

**Issue by blazv** [openbaton/NFVO#11]
After we lunch the NS Descriptor from Catalogue tab VNF Packages are multiplied.
Before the NSD is launched:
![m_vnfp_0](https://cloud.githubusercontent.com/assets/16189252/11954302/bbc71120-a8a7-11e5-8be3-8ea1cf0948c5.JPG)
Launching NSD:
![m_vnfp_1](https://cloud.githubusercontent.com/assets/16189252/11954307/bfde80d6-a8a7-11e5-8cb6-50e408d0f16c.JPG)
VNFP after NSD is launched.
![m_vnfp_2](https://cloud.githubusercontent.com/assets/16189252/11954309/c11e4d32-a8a7-11e5-8ab8-32e12fe50ff2.JPG)

Regards, BlazV

**Comment by lorenzotomasini** [comment]
The duplicate VNF packages aren't really duplicate. there are 2 of them referring the VNFDs, the first ones. Then we decided to create new VNF Packages for the VNFRs, that explains the "duplicate" entries in the Dashboard once the NSR is launched/created. We recognize anyway that this isn't intuitive so in the next minor release we will find a different design in order to avoid this misunderstanding. 
Thank you for pointing us to that.

Lorenzo

**Comment by KLuka** [comment]
This is solved in 2.0.2.
