### ISSUE TITLE
RuntimeException: No EMS yet for host

### ISSUE THREAD

**Issue by onurko** [openbaton/NFVO#145]
Hello,

After onboarding CSAR file, runtime exception appeared for the message between generic VNFM and EMS. After throwing this exception, on boarding process is halted and VNFM sent ERROR message to VNFR .

Is there any way to handle this problem?

[EMS_problem.txt](https://github.com/openbaton/NFVO/files/964226/EMS_problem.txt)

Thank you,

Onur

**Comment by onurko** [comment]
Any suggestion on that?

**Comment by gc4rella** [comment]
Hi, most of the time this is due to two main reasons: 
* EMS not properly installed/configured inside the VM where the VNF should be installed. For troubleshooting, I suggest you to ssh into the VM and check that the EMS configuration file is present (under /etc/openbaton/ems) and the conf.ini file is properly configured. Please paste if possible the content of that file. The installation/configuration of the EMS happens while the VM is booting using the cloud-init functionality. 
* in that file (conf.ini) you should see that there is a parameter orch_ip which is actually the IP of RabbitMQ. This IP must be reachable from the VM network, so that the EMS can register to the VNFM. If this IP is not set correctly (for instance is set to localhost), you should configure the NFVO/VNFM configuration files (rabbitmq related paramters) accordingly. http://openbaton.github.io/documentation/nfvo-configuration/

**Comment by alidiab90** [comment]
I have the same problem. 
EMS is installed, I see the file (/etc/openbaton/ems/confi.ini):  
[ems]
orch_ip = localhost
orch_port = 61613
type = generic
hostname = newName1

I did not understand well what should I do, can you explain please.

**Comment by gc4rella** [comment]
Please check my comment in issue #167
