### ISSUE TITLE
Brew install fail on MacOS

### ISSUE THREAD

**Issue by djKooks** [openbaton/NFVO#218]
Hello,
Does anyone knows about issue below?
```
$ brew install http://get.openbaton.org/homebrew/openbaton-nfvo.rb
...
SHA256 mismatch
Expected: 42cc4c871c698e6f40604a7b4091cdb0b115afe5402d94d446c59e4b08b9105e
Actual: 6ce5d3a341fb52e37715a03deaa8b36f827453158192ffd0dd144a020e167800
Archive: /Users/kwangin/Library/Caches/Homebrew/openbaton-nfvo-4.0.0.0
To retry an incomplete download, remove the file above.
```

I tried `brew update`, but it still shows same problem. I'm not sure this problem of `brew` or not. Is there somebody knows about this?

Thanks.

**Comment by djKooks** [comment]
Or is there a way to install via source?

**Comment by marcellom** [comment]
Hi @djKooks, this is an issue due to SHA256 mismatch. Probably because the same file has been uploaded multiple time. I need to replicate the issue and fix it.

> Or is there a way to install via source?

Sure, you can clone the repository and compile it using `./openbaton.sh compile`. Then you need to configure the NFVO manually. The configuration is explained here: http://openbaton.github.io/documentation/nfvo-configuration/

**Comment by gc4rella** [comment]
@djKooks you can also use docker, which allows you to setup quickly an all-in-one environment for starting playing with OB: http://openbaton.github.io/documentation/nfvo-installation-docker/

I'm using it on my mac.

**Comment by marcellom** [comment]
I updated the brew formula, this issue has been fixed, it was a SHA256 mismatch.

**Comment by djKooks** [comment]
@gc4rella @marcellom Thanks!
