### ISSUE TITLE
Mismatch IPs on Scaling

### ISSUE THREAD

**Issue by wittling** [openbaton/NFVO#229]
I was recently testing the AutoScaling and ran into this issue, which I will record here.

Use Case:
Set descriptor for AutoScaling (in my case, scaling value was set to 8 - with an initial value of 2).

As the VMs scaled to 8, I went to the GUI and used the +/- button functionality to pull the number of VMs down to 6 (using minus button). I then went and hit the + (add) button, and added an IP address of 192.168.178.251 (network was defined as a 192.168.178.0/24 in OpenStack). This IP was not in the range of IPs I had configured on OpenStack, so OpenStack decided to give the VM an IP Address of 192.168.178.25.  But the GUI still had the initial user input value of 192.168.178.251.

I guess there needs to be either an additional follow-up API call to OpenStack, or some kind of event driven notification (from where I don't know) that allows the GUI to update the IP address with the IP that OpenStack ultimately assigns to that instance.

**Comment by lorenzotomasini** [comment]
Hello, 

Was it a floating IP?

**Comment by wittling** [comment]
Actually no. I had no floating IPs set up on that network. The network in Openstack has a range of 192.168.178.0/24. The DHCP range is .11-.49. Openstack assigns one port (.254) to the router, and another for DHCP. The only floating IPs I have on Openstack are for a different network. If I instantiate 3 VMs and get 192.168.178.11-14 and then scale up, I would expect to get 15, 16, 17, etc (Openstack will skip ports in use). If I hit the plus button to add an additional, why would it not just do the same thing? And return an error if the range is eexhaisted? Why the need to specify a floating up on dsxnet when I hit plus button when I never had to specify floating IPs in the descriptor?

**Comment by lorenzotomasini** [comment]
>  If I hit the plus button to add an additional, why would it not just do the same thing?

That is what it happens. the deploy NSR execute a launchVM for each VMs inside the VNFDs. When doing the scale out the same method is invoked for one (or maybe more) VM for only one VNF.

>And return an error if the range is eexhaisted?

If you did not specify the fixed Ip in the descriptor, and i assume you didn't because of scaling out, we are not taking care of choosing the private ip on the chosen network. We simply invoke Openstack4j lib methods for allocating a VM using specific networks, sec_groups, image id, flavour etc

> Why the need to specify a floating up on dsxnet when I hit plus button when I never had to specify floating IPs in the descriptor?

you don't need to, you can leave the fip field empty and it should not be allocated any

>  If I instantiate 3 VMs and get 192.168.178.11-14 and then scale up, I would expect to get 15, 16, 17, etc 

I would not expect these exact IPs, since we are not asking Openstack to allocate some precise fixed IPs if not specified in the descriptor. I would expect them to be in the range specified in the chosen subnet in Openstack. If this is not the case, as i understand from the issue, it is not related with our code, but more an Openstack / Openstack4j issue. You can see [here](https://github.com/openbaton/openstack4j-plugin/blob/master/src/main/java/org/openbaton/drivers/openstack4j/OpenStack4JDriver.java#L218-L300) the steps we follow for creating a VM.

I hope I understood correctly the point. 
If I have missed something let us know and excuse us for the late answer

**Comment by mpauls** [comment]
Was clarified and can be closed I think
