### ISSUE TITLE
NFVO installed by docker compose fails to start second time

### ISSUE THREAD

**Issue by RuthDevlaeminck** [openbaton/NFVO#250]
When launching using docker-compose using the min-compose.yml file it successfully launches the first time.  
```
HOST_IP=192.168.254.11 docker-compose -f min-compose.yml up -d
```

When you do

```
docker-compose -f min-compose.yml down
HOST_IP=192.168.254.11 docker-compose -f min-compose.yml up -d
```

The NFVO will not come up.  Attaching error log
[openbaton5_1_4_restart.log](https://github.com/openbaton/NFVO/files/1613094/openbaton5_1_4_restart.log)

**Comment by marcellom** [comment]
Hi, can you provide the docker compose file please? So that we can try to reproduce the error.

**Comment by gc4rella** [comment]
@marcellom the min-compose file is the one available in the bootstrap project: https://github.com/openbaton/bootstrap/tree/develop/distributions/docker/compose

**Comment by marcellom** [comment]
That docker file works for me, even if I restart it twice. I have just added (https://github.com/openbaton/bootstrap/commit/9413c93e87d86ad3e3ec82c6296af0f7c7099d2f) the property for updating the db instead of dropping it every restart. From the log you provided I see a problem with Flyway, meaning that probably you are starting different version of the NFVO with the same db. Unless you have important info in the db, try to clear the content of the folder ./dbdata_nfvo and start the docker compose again.

**Comment by RuthDevlaeminck** [comment]
I just created a new box and installed using docker.  It seems to be working just fine now so I will close the issue.
