### ISSUE TITLE
Display error reason for NSR in ERROR state

### ISSUE THREAD

**Issue by KLuka** [openbaton/NFVO#34]
When NSR goes to ERROR state user needs to manually check log files to see what went wrong. It would be very useful, if error reason could be retrieved from OpenBaton API or even displayed on dashboard (maybe under NRS details).

**Comment by lorenzotomasini** [comment]
Hello,

From version 3, a short error reason description is displayed in the last executed action of the nsr page. Moreover you can check the scripts log/error messages if you go nsr->vnfr->vdu->vnfc instance-> view logs. In that page the standard error of the script or the standard output if no errors happened is shown

**Comment by DasSnehashish** [comment]
for me also same is showing ,why it is showing that i know from my analysis . it is showing becoz EMS project is not successfully installed in the newly created VM . this two operaton are happing happly
1)GRANT_OPERATION message: 
2)ALLOCATE_RESOURCE message:
after this happen it is trying to search the EMS in up or not but it is finding EMS is not in up state ,..that's why some error will come in GVNFM side .. and GVNFM  will send statuss as "ERROR" .to NFVO

for this issue i wrise a concer  in  github ...see that one you can understand .i think

**Comment by gc4rella** [comment]
Please provide logs of: 
* Orchestrator
* generic-vnfm
* vm boot log: you can gather it from the openstack dashboard clicking on the log section of the specific VM

**Comment by lorenzotomasini** [comment]
Then I believe we can close this issue

**Comment by KLuka** [comment]
I can confirm that according to tests with version 3. Thanks 👍
