### ISSUE TITLE
Wrong Error on uploading NSD with not supported content

### ISSUE THREAD

**Issue by ranzpirat** [openbaton/NFVO#40]
When trying to upload a NSD with `"vimInstanceName": "gen_datacenter"` instead of `"vimInstanceName": ["gen_datacenter"]` in the VDU, the following error is shown: `ERROR: HTTP status: 400 response data: Bad request: your json is not well formatted`

Which is wrong because the json is well formatted (checked with a linter) but simply not accepted.

**Comment by DasSnehashish** [comment]
after Registering the VIM to NFVO ,what  name it is show in Dashboard ,that name you need to pass ,
for me like this "vimInstanceName": ["OpenStack-Vim"].if you want the NSD file i can share you send me you a mail in this ID snehashish.das@sawridgesystems.com

**Comment by gc4rella** [comment]
@radoslavvlaskovski what's the status?

**Comment by radoslavvlaskovski** [comment]
After investigation we saw that the problem could not be handled on the backend, because the json is rejected right away because when passing a parameter(this is not just for the "vimInstanceName") as a String instead of an array it gets rejected immediately, because it does not follow the model.  
At the moment the error shown is:
"An error occured and could not be handled properly, please, report to us and we will fix it as soon as possible".
